### ISSUE TITLE
File loading error after update

### ISSUE THREAD

**Issue by Hipapheralkus** [augustd/burp-suite-error-message-checks#26]
The old version was working quite wall, but now after I updated to 2.0.0 I have following trace in output log:
```
Restoring settings...
Loaded URL: file:///C:\Burp\burp-suite-error-message-checks.tab
```

and in Error log: 
```
java.lang.IllegalArgumentException: Invalid protocol: file
	at burp.bkb.makeHttpRequest(Unknown Source)
	at com.codemagi.burp.RuleTableComponent.loadMatchRules(RuleTableComponent.java:111)
	at com.codemagi.burp.RuleTableComponent.<init>(RuleTableComponent.java:55)
	at burp.BurpExtender.initPassiveScan(BurpExtender.java:45)
	at com.codemagi.burp.PassiveScan.initialize(PassiveScan.java:37)
	at com.codemagi.burp.BaseExtender.registerExtenderCallbacks(BaseExtender.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.mch.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
java.lang.IllegalArgumentException: Invalid protocol: file
	at burp.bkb.makeHttpRequest(Unknown Source)
	at com.codemagi.burp.RuleTableComponent.loadMatchRules(RuleTableComponent.java:111)
	at com.codemagi.burp.RuleTableComponent.<init>(RuleTableComponent.java:55)
	at burp.BurpExtender.initPassiveScan(BurpExtender.java:45)
	at com.codemagi.burp.PassiveScan.initialize(PassiveScan.java:37)
	at com.codemagi.burp.BaseExtender.registerExtenderCallbacks(BaseExtender.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at burp.mch.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

GUI tab won't open for me any more. And the reason I needed to load it locally from file is because the testing instance of Burp doesn't have direct access to the internet.

**Comment by augustd** [comment]
HI @Hipapheralkus, This issue was probably introduced by fixing #20, which loads the match rules using Burp's internal HTTP (so it can take advantage of Burp's proxy configuration). Are you now able to load the match rules directly from the repo URL? 

https://raw.githubusercontent.com/augustd/burp-suite-error-message-checks/master/src/main/resources/burp/match-rules.tab

I've also added a new feature to load the match rules from within the BApp jar itself (See #27). That should be considered a backup, since the match rules will only be updated when a new jar is built.
